CREATE TABLE IF NOT EXISTS companies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  stock_id VARCHAR(10) NOT NULL UNIQUE COMMENT '有價證券代號',
  name VARCHAR(255) NOT NULL COMMENT '公司名稱',
  isin_code VARCHAR(20) COMMENT '國際證券辨識號碼(ISIN)',
  listing_date DATE COMMENT '上市日',
  market_type VARCHAR(50) COMMENT '市場別',
  industry VARCHAR(100) COMMENT '產業別',
  cfi_code VARCHAR(20) COMMENT 'CFICode',
  is_listed BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);